require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

# Exclude files that contain purely declarative DSLs
# see https://stackoverflow.com/a/41187163 for more details
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'

# I don't like the approach of forcing the first describe block to point to a class. In some cases specs are more
# flexible if they describe an abstract behavior rather than a specific class
RSpec/DescribeClass:
  Enabled: false

# I don't agree with the approach of having only one assert per test, in some cases you need to perform more than
# one verification to ensure the whole functionality works as intended
RSpec/MultipleExpectations:
  Enabled: false

# I like the idea of restricting the amount of nested groups, but 3 seems too low
RSpec/NestedGroups:
  Max: 5

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
